reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit)

opt_in_rules:
  - closure_end_indentation
  - closure_spacing
  - empty_count
  - explicit_init
  - fatal_error_message
  - first_where
  - implicitly_unwrapped_optional
  - multiline_parameters
  - nesting
  - number_separator
  - operator_usage_whitespace
  - overridden_super_call
  - private_outlet
  - protocol_property_accessors_order
  - redundant_nil_coalescing
  - sorted_imports
  - syntactic_sugar
  - vertical_whitespace
  - force_unwrapping

disabled_rules: # rule identifiers to exclude from running
  - function_parameter_count
  - implicit_getter
  - sorted_imports
  - void_return
  - unused_optional_binding
  - multiple_closures_with_trailing_closure
  - notification_center_detachment
  - extension_access_modifier
  - redundant_set_access_control
  - closure_end_indentation
  - for_where
  - switch_case_on_newline
  - switch_case_alignment

force_cast: error
force_try: error
force_unwrapping: error

cyclomatic_complexity:
  ignores_case_statements: true
  warning: 20

file_length:
  warning: 500
  error: 800

line_length:
  warning: 150
  error: 180
  ignores_comments: true
  ignores_urls: true

function_body_length:
  warning: 100
  error: 150

nesting:
  type_level:
    warning: 4
    error: 6
  function_level:
    warning: 6
    error: 10

identifier_name:
  allowed_symbols: "_"
  min_length: 3
  max_length:
    warning: 90
    error: 1000
  excluded:
    - r
    - g
    - b
    - a
    - id
    - i
    - up
    - to
    - in
    - x
    - y
    - z
    - by
    - at
    - as
    - on
    - tv

type_name:
  allowed_symbols: "_"
  min_length: 3 # only warning
  max_length: # warning and error
    warning: 50
    error: 60
  excluded:  # excluded via strin
    - RGB
    - HSV
    - Bit
    - Age
    - T
    - V

implicitly_unwrapped_optional:
  mode: all_except_iboutlets
  severity: error

large_tuple:
  warning: 4
  error: 5

type_body_length:
  warning: 1000
  error: 1000

trailing_comma:
  mandatory_comma: false

number_separator:
  minimum_length: 8

private_outlet:
  allow_private_set: false

trailing_whitespace:
  ignores_empty_lines: false
  ignores_comments: true

custom_rules:
  explicit_failure_calls:
      name: “Avoid asserting ‘false’”
      regex: ‘((assert|precondition)\(false)’
      message: “Use assertionFailure() or preconditionFailure() instead.”
      severity: warning
  comments_space:
      name: "Space After Comment"
      regex: '(^ *//\w+)'
      message: "There should be a space after //"
      severity: error
  empty_line_after_guard:
      name: "Empty Line After Guard"
      regex: '(^ *guard[ a-zA-Z0-9=?.\(\),><!]*\{[ a-zA-Z0-9=?.\(\),><!]*\}\n *(?!(?:return|guard))\S+)'
      message: "There should be an empty line after a guard"
      severity: error
  print_prohibition:
    regex: '^[^/\n]*print'
    message: "Use debugPrint or MPLog instead"
    severity: warning
  class_protocol:
    regex: ': class'
    message: "class is deprecated for iOS, use AnyObject instead"